// 内置食物库与活动库
import { getCustomFoods } from './store.js';

export const FOOD_DB = [
  { id: 'egg', name: '鸡蛋', category: '蛋奶', tags: ['早餐'], kcal: 144, protein: 13, fat: 9, carb: 1, icon: '🥚' },
  { id: 'chicken_breast', name: '鸡胸肉', category: '肉禽', kcal: 165, protein: 31, fat: 3.6, carb: 0, icon: '🍗' },
  { id: 'rice_cooked', name: '米饭(熟)', category: '主食', kcal: 116, protein: 2.6, fat: 0.3, carb: 25.6, icon: '🍚' },
  { id: 'milk_whole', name: '牛奶(全脂)', category: '蛋奶', tags: ['早餐'], kcal: 61, protein: 3.2, fat: 3.3, carb: 4.8, icon: '🥛' },
  { id: 'oatmeal', name: '燕麦', category: '主食', tags: ['早餐'], kcal: 389, protein: 16.9, fat: 6.9, carb: 66, icon: '🥣' },
  { id: 'banana', name: '香蕉', category: '蔬果', tags: ['早餐'], kcal: 89, protein: 1.1, fat: 0.3, carb: 22.8, icon: '🍌' },
  { id: 'broccoli', name: '西兰花', category: '蔬果', kcal: 34, protein: 2.8, fat: 0.4, carb: 7, icon: '🥦' },
  { id: 'peanut', name: '花生', category: '坚果', kcal: 567, protein: 25.8, fat: 49.2, carb: 16.1, icon: '🥜' },
  { id: 'beef_steak', name: '牛排', category: '肉禽', kcal: 250, protein: 26, fat: 15, carb: 0, icon: '🥩' },
  { id: 'salmon', name: '三文鱼', category: '水产', kcal: 208, protein: 20, fat: 13, carb: 0, icon: '🐟' },
  { id: 'tofu', name: '豆腐', category: '豆制品', kcal: 76, protein: 8, fat: 4.8, carb: 1.9, icon: '🧊' },
  { id: 'bread', name: '全麦面包', category: '主食', tags: ['早餐'], kcal: 247, protein: 13, fat: 3.4, carb: 41, icon: '🍞' },
  { id: 'apple', name: '苹果', category: '蔬果', tags: ['早餐'], kcal: 52, protein: 0.3, fat: 0.2, carb: 13.8, icon: '🍎' },
  { id: 'yogurt', name: '酸奶(无糖)', category: '蛋奶', tags: ['早餐'], kcal: 59, protein: 10, fat: 0, carb: 3.6, icon: '🍶' },
  { id: 'sweet_potato', name: '红薯(熟)', category: '主食', tags: ['早餐'], kcal: 86, protein: 1.6, fat: 0.1, carb: 20.1, icon: '🍠' },
  { id: 'pasta_cooked', name: '意面(熟)', category: '主食', kcal: 158, protein: 5.8, fat: 0.9, carb: 31, icon: '🍝' },
  { id: 'spinach', name: '菠菜', category: '蔬果', kcal: 23, protein: 2.9, fat: 0.4, carb: 3.6, icon: '🥬' },
  { id: 'avocado', name: '牛油果', category: '蔬果', kcal: 160, protein: 2, fat: 14.7, carb: 8.5, icon: '🥑' },
  { id: 'almond', name: '杏仁', category: '坚果', kcal: 579, protein: 21.2, fat: 49.9, carb: 21.6, icon: '🌰' },
  { id: 'shrimp', name: '虾仁', category: '水产', kcal: 99, protein: 24, fat: 0.3, carb: 0, icon: '🍤' },
  { id: 'pork_tenderloin', name: '猪里脊', category: '肉禽', kcal: 143, protein: 26, fat: 3.5, carb: 0, icon: '🥓' },
  { id: 'quinoa_cooked', name: '藜麦(熟)', category: '主食', kcal: 120, protein: 4.4, fat: 1.9, carb: 21.3, icon: '🌾' },
  { id: 'carrot', name: '胡萝卜', category: '蔬果', kcal: 41, protein: 0.9, fat: 0.2, carb: 9.6, icon: '🥕' },
  { id: 'cottage_cheese', name: '茅屋奶酪', category: '蛋奶', kcal: 98, protein: 11, fat: 4.3, carb: 3.4, icon: '🧀' },
  { id: 'protein_powder', name: '蛋白粉', category: '补剂', kcal: 375, protein: 85, fat: 3, carb: 5, icon: '🥤' },
  { id: 'chocolate_dark', name: '黑巧克力', category: '零食', kcal: 546, protein: 4.9, fat: 31, carb: 61, icon: '🍫' },
  { id: 'olive_oil', name: '橄榄油', category: '油脂', kcal: 884, protein: 0, fat: 100, carb: 0, icon: '🫒' },
  { id: 'honey', name: '蜂蜜', category: '调味品', kcal: 304, protein: 0.3, fat: 0, carb: 82.4, icon: '🍯' },
  { id: 'potato_cooked', name: '土豆(熟)', category: '主食', kcal: 87, protein: 1.9, fat: 0.1, carb: 20.1, icon: '🥔' },
  { id: 'cucumber', name: '黄瓜', category: '蔬果', kcal: 15, protein: 0.7, fat: 0.1, carb: 3.6, icon: '🥒' },
  { id: 'tomato', name: '番茄', category: '蔬果', kcal: 18, protein: 0.9, fat: 0.2, carb: 3.9, icon: '🍅' },
  { id: 'mushroom', name: '香菇', category: '蔬果', kcal: 26, protein: 2, fat: 0.3, carb: 4.8, icon: '🍄' },
  { id: 'orange', name: '橙子', category: '蔬果', kcal: 47, protein: 0.9, fat: 0.1, carb: 11.8, icon: '🍊' },
  { id: 'grapes', name: '葡萄', category: '蔬果', kcal: 69, protein: 0.7, fat: 0.2, carb: 18.1, icon: '🍇' },
  { id: 'steamed_bun', name: '馒头', category: '主食', tags: ['早餐'], kcal: 223, protein: 7, fat: 1.1, carb: 47, icon: '🥟' },
  { id: 'dumpling', name: '水饺', category: '主食', tags: ['早餐'], kcal: 200, protein: 8, fat: 8, carb: 24, icon: '🥟' },
  { id: 'noodle_cooked', name: '面条(熟)', category: '主食', tags: ['早餐'], kcal: 137, protein: 4.5, fat: 0.2, carb: 28, icon: '🍜' },
  { id: 'lettuce', name: '生菜', category: '蔬果', kcal: 15, protein: 1.4, fat: 0.2, carb: 2.9, icon: '🥗' },
  { id: 'eggplant', name: '茄子', category: '蔬果', kcal: 25, protein: 1, fat: 0.2, carb: 6, icon: '🍆' },
  { id: 'corn', name: '玉米(熟)', category: '主食', tags: ['早餐'], kcal: 112, protein: 4, fat: 1.2, carb: 22.8, icon: '🌽' },
  { id: 'mango', name: '芒果', category: '蔬果', kcal: 60, protein: 0.8, fat: 0.4, carb: 15, icon: '🥭' },
  { id: 'strawberry', name: '草莓', category: '蔬果', kcal: 32, protein: 0.7, fat: 0.3, carb: 7.7, icon: '🍓' },
  { id: 'blueberry', name: '蓝莓', category: '蔬果', kcal: 57, protein: 0.7, fat: 0.3, carb: 14.5, icon: '🫐' },
  { id: 'ramen', name: '拉面', category: '主食', kcal: 436, protein: 10, fat: 15, carb: 66, icon: '🍜' },
  { id: 'pizza', name: '披萨', category: '快餐', kcal: 266, protein: 11, fat: 10, carb: 33, icon: '🍕' },
  { id: 'burger', name: '汉堡', category: '快餐', kcal: 295, protein: 17, fat: 14, carb: 24, icon: '🍔' },
  { id: 'fries', name: '薯条', category: '快餐', kcal: 312, protein: 3.4, fat: 15, carb: 41, icon: '🍟' },
  { id: 'sushi', name: '寿司', category: '快餐', kcal: 143, protein: 5, fat: 0.5, carb: 28, icon: '🍣' },
  { id: 'ice_cream', name: '冰淇淋', category: '零食', kcal: 207, protein: 3.5, fat: 11, carb: 24, icon: '🍦' },

  // 家常菜
  { id: 'tomato_egg', name: '番茄炒蛋', category: '家常菜', kcal: 150, protein: 8, fat: 10, carb: 6, icon: '🍳' },
  { id: 'pepper_pork', name: '辣椒炒肉', category: '家常菜', kcal: 180, protein: 12, fat: 12, carb: 4, icon: '🌶️' },
  { id: 'braised_pork', name: '红烧肉', category: '家常菜', kcal: 350, protein: 15, fat: 28, carb: 5, icon: '🥓' },
  { id: 'kung_pao_chicken', name: '宫保鸡丁', category: '家常菜', kcal: 180, protein: 14, fat: 10, carb: 8, icon: '🍗' },
  { id: 'fish_flavored_shreds', name: '鱼香肉丝', category: '家常菜', kcal: 170, protein: 12, fat: 8, carb: 12, icon: '🍖' },
  { id: 'mapo_tofu', name: '麻婆豆腐', category: '家常菜', kcal: 120, protein: 8, fat: 8, carb: 4, icon: '🌶️' },
  { id: 'green_pepper_pork', name: '青椒炒肉', category: '家常菜', kcal: 160, protein: 12, fat: 10, carb: 5, icon: '🌶️' },
  { id: 'shredded_potato', name: '炒土豆丝', category: '家常菜', kcal: 90, protein: 2, fat: 4, carb: 12, icon: '🥔' },
  { id: 'sour_cabbage', name: '醋溜白菜', category: '家常菜', kcal: 45, protein: 2, fat: 1, carb: 7, icon: '🥬' },
  { id: 'garlic_broccoli', name: '蒜蓉西兰花', category: '家常菜', kcal: 55, protein: 3, fat: 1, carb: 8, icon: '🥦' },
  { id: 'cola_chicken_wings', name: '可乐鸡翅', category: '家常菜', kcal: 220, protein: 15, fat: 14, carb: 6, icon: '🍗' },
  { id: 'braised_ribs', name: '红烧排骨', category: '家常菜', kcal: 280, protein: 18, fat: 20, carb: 4, icon: '🥓' },
  { id: 'twice_cooked_pork', name: '回锅肉', category: '家常菜', kcal: 320, protein: 14, fat: 26, carb: 4, icon: '🥓' },
  { id: 'hand_torn_cabbage', name: '手撕包菜', category: '家常菜', kcal: 70, protein: 2, fat: 4, carb: 7, icon: '🥬' },
  { id: 'di_san_xian', name: '地三鲜', category: '家常菜', kcal: 110, protein: 3, fat: 5, carb: 14, icon: '🥘' },
  { id: 'wood_mustard_meat', name: '木须肉', category: '家常菜', kcal: 140, protein: 10, fat: 8, carb: 6, icon: '🍖' },
  { id: 'dry_fried_beans', name: '干煸豆角', category: '家常菜', kcal: 120, protein: 4, fat: 6, carb: 13, icon: '🌶️' },
  { id: 'boiled_fish', name: '水煮鱼', category: '家常菜', kcal: 160, protein: 16, fat: 8, carb: 3, icon: '🐟' },
  { id: 'pickled_fish', name: '酸菜鱼', category: '家常菜', kcal: 140, protein: 14, fat: 6, carb: 4, icon: '🐟' },
  { id: 'garlic_shrimp', name: '蒜蓉粉丝虾', category: '家常菜', kcal: 130, protein: 12, fat: 3, carb: 13, icon: '🍤' },
  { id: 'smashed_cucumber', name: '拍黄瓜', category: '家常菜', kcal: 35, protein: 1, fat: 1, carb: 4, icon: '🥒' },
  { id: 'wood_ear_salad', name: '凉拌木耳', category: '家常菜', kcal: 40, protein: 1, fat: 1, carb: 6, icon: '🍄' },
  { id: 'tomato_egg_soup', name: '西红柿鸡蛋汤', category: '家常菜', kcal: 35, protein: 2, fat: 2, carb: 2, icon: '🍲' },
  { id: 'seaweed_egg_soup', name: '紫菜蛋花汤', category: '家常菜', kcal: 25, protein: 2, fat: 1, carb: 1, icon: '🍲' },
  { id: 'egg_fried_rice', name: '蛋炒饭', category: '家常菜', kcal: 180, protein: 6, fat: 7, carb: 22, icon: '🍳' },
  { id: 'fried_noodles', name: '炒面', category: '家常菜', kcal: 160, protein: 5, fat: 5, carb: 23, icon: '🍜' },
  { id: 'steamed_bun2', name: '包子', category: '主食', tags: ['早餐'], kcal: 220, protein: 7, fat: 6, carb: 33, icon: '🥟' },
  { id: 'flower_roll', name: '花卷', category: '主食', tags: ['早餐'], kcal: 220, protein: 7, fat: 4, carb: 42, icon: '🥟' },
  { id: 'white_porridge', name: '白粥', category: '主食', tags: ['早餐'], kcal: 46, protein: 1, fat: 0.3, carb: 10, icon: '🥣' },
  { id: 'pancake', name: '煎饼', category: '主食', tags: ['早餐'], kcal: 290, protein: 8, fat: 10, carb: 42, icon: '🥞' },
  { id: 'fried_dough_stick', name: '油条', category: '主食', tags: ['早餐'], kcal: 388, protein: 6, fat: 18, carb: 51, icon: '🥖' },
  { id: 'soy_milk', name: '豆浆', category: '蛋奶', tags: ['早餐'], kcal: 30, protein: 3, fat: 1.5, carb: 1.5, icon: '🥤' },
  { id: 'tofu_pudding', name: '豆腐脑', category: '豆制品', tags: ['早餐'], kcal: 50, protein: 4, fat: 2, carb: 3, icon: '🧊' },
  { id: 'liangpi', name: '凉皮', category: '小吃', kcal: 120, protein: 4, fat: 2, carb: 22, icon: '🍜' },
  { id: 'roujiamo', name: '肉夹馍', category: '小吃', tags: ['早餐'], kcal: 250, protein: 10, fat: 10, carb: 30, icon: '🥙' },
  { id: 'hot_dry_noodles', name: '热干面', category: '小吃', tags: ['早餐'], kcal: 300, protein: 10, fat: 14, carb: 35, icon: '🍜' },
  { id: 'snail_noodles', name: '螺蛳粉', category: '小吃', kcal: 350, protein: 8, fat: 15, carb: 45, icon: '🍜' },
  { id: 'instant_noodles', name: '方便面', category: '快餐', kcal: 450, protein: 10, fat: 20, carb: 60, icon: '🍜' },
  { id: 'sandwich2', name: '三明治', category: '快餐', tags: ['早餐'], kcal: 250, protein: 12, fat: 10, carb: 26, icon: '🥪' },
  { id: 'veg_salad', name: '蔬菜沙拉', category: '轻食', kcal: 50, protein: 2, fat: 0.5, carb: 8, icon: '🥗' },
  { id: 'fried_chicken', name: '炸鸡', category: '快餐', kcal: 280, protein: 18, fat: 18, carb: 8, icon: '🍗' },
  { id: 'milk_tea', name: '奶茶', category: '饮品', kcal: 55, protein: 2, fat: 2, carb: 7, icon: '🧋' },
  { id: 'coke', name: '可乐', category: '饮品', kcal: 42, protein: 0, fat: 0, carb: 10.6, icon: '🥤' },
  { id: 'fruit_juice', name: '果汁', category: '饮品', kcal: 45, protein: 0.5, fat: 0.1, carb: 11, icon: '🧃' },
  { id: 'beer', name: '啤酒', category: '饮品', kcal: 43, protein: 0.5, fat: 0, carb: 3.6, icon: '🍺' },
  { id: 'stir_fried_veg', name: '清炒时蔬', category: '家常菜', kcal: 50, protein: 2, fat: 1, carb: 8, icon: '🥬' },
  { id: 'garlic_spinach', name: '蒜蓉菠菜', category: '家常菜', kcal: 55, protein: 3, fat: 1, carb: 8, icon: '🥬' },
  { id: 'sweet_sour_pork', name: '糖醋里脊', category: '家常菜', kcal: 250, protein: 12, fat: 12, carb: 18, icon: '🥓' },
  { id: 'onion_egg', name: '洋葱炒蛋', category: '家常菜', kcal: 130, protein: 7, fat: 9, carb: 5, icon: '🍳' },
  { id: 'chive_egg', name: '韭菜炒鸡蛋', category: '家常菜', kcal: 140, protein: 8, fat: 10, carb: 4, icon: '🍳' },
  { id: 'winter_melon_rib_soup', name: '冬瓜排骨汤', category: '家常菜', kcal: 80, protein: 6, fat: 4, carb: 4, icon: '🍲' },
  { id: 'corn_rib_soup', name: '玉米排骨汤', category: '家常菜', kcal: 90, protein: 6, fat: 4, carb: 7, icon: '🍲' },
  { id: 'tomato_beef_brisket', name: '番茄牛腩', category: '家常菜', kcal: 150, protein: 12, fat: 8, carb: 5, icon: '🥩' },
  { id: 'curry_chicken', name: '咖喱鸡肉', category: '家常菜', kcal: 140, protein: 12, fat: 7, carb: 6, icon: '🍛' },
  { id: 'teriyaki_chicken', name: '照烧鸡腿', category: '家常菜', kcal: 180, protein: 16, fat: 9, carb: 5, icon: '🍗' },
  { id: 'braised_egg', name: '卤蛋', category: '蛋奶', tags: ['早餐'], kcal: 160, protein: 13, fat: 11, carb: 1, icon: '🥚' },
  { id: 'tea_egg', name: '茶叶蛋', category: '蛋奶', tags: ['早餐'], kcal: 140, protein: 12, fat: 9, carb: 1, icon: '🥚' },
  { id: 'salted_duck_egg', name: '咸鸭蛋', category: '蛋奶', tags: ['早餐'], kcal: 180, protein: 12, fat: 14, carb: 1, icon: '🥚' },
  { id: 'blanched_shrimp', name: '白灼虾', category: '水产', kcal: 90, protein: 18, fat: 0.5, carb: 0, icon: '🍤' },
  { id: 'steamed_fish', name: '清蒸鱼', category: '水产', kcal: 120, protein: 18, fat: 4, carb: 1, icon: '🐟' },
  { id: 'braised_fish', name: '红烧鱼', category: '家常菜', kcal: 160, protein: 16, fat: 8, carb: 3, icon: '🐟' },
  { id: 'garlic_scallop', name: '蒜蓉扇贝', category: '水产', kcal: 110, protein: 12, fat: 2, carb: 8, icon: '🦪' },
  { id: 'steamed_egg', name: '蒸蛋羹', category: '蛋奶', tags: ['早餐'], kcal: 70, protein: 6, fat: 5, carb: 1, icon: '🥚' },
  { id: 'fried_egg', name: '煎蛋', category: '蛋奶', tags: ['早餐'], kcal: 190, protein: 13, fat: 15, carb: 1, icon: '🍳' },
  { id: 'poached_egg', name: '荷包蛋', category: '蛋奶', tags: ['早餐'], kcal: 195, protein: 13, fat: 15, carb: 1, icon: '🍳' },
  { id: 'soft_boiled_egg', name: '糖心蛋', category: '蛋奶', tags: ['早餐'], kcal: 145, protein: 13, fat: 10, carb: 1, icon: '🥚' }
];

export const ACTIVITY_DB = [
  { id: 'walk', name: '步行', met: 3.5, icon: '🚶' },
  { id: 'jog', name: '慢跑', met: 7.0, icon: '🏃' },
  { id: 'cycle', name: '骑行', met: 7.5, icon: '🚴' },
  { id: 'strength', name: '力量训练', met: 5.0, icon: '🏋️' },
  { id: 'swim', name: '游泳', met: 8.0, icon: '🏊' },
  { id: 'yoga', name: '瑜伽', met: 2.5, icon: '🧘' },
  { id: 'hiit', name: 'HIIT', met: 11.0, icon: '🔥' },
  { id: 'housework', name: '家务', met: 2.3, icon: '🧹' },
  { id: 'dance', name: '跳舞', met: 5.5, icon: '💃' },
  { id: 'hike', name: '徒步', met: 6.0, icon: '🥾' },
  { id: 'boxing', name: '拳击', met: 9.0, icon: '🥊' },
  { id: 'basketball', name: '篮球', met: 6.5, icon: '🏀' },
  { id: 'football', name: '足球', met: 7.0, icon: '⚽' },
  { id: 'badminton', name: '羽毛球', met: 5.5, icon: '🏸' },
  { id: 'climb', name: '爬楼梯', met: 8.0, icon: '🪜' },
  { id: 'clean', name: '大扫除', met: 3.0, icon: '🧼' }
];

export const MEAL_LABELS = {
  breakfast: '早餐',
  lunch: '午餐',
  dinner: '晚餐',
  snack: '加餐'
};

export const MEAL_ICONS = {
  breakfast: '🌅',
  lunch: '🌞',
  dinner: '🌙',
  snack: '✨'
};

const ICON_MAP = [
  { icon: '🍑', keywords: ['桃', '水蜜桃', '黄桃'] },
  { icon: '🍎', keywords: ['苹果', '苹'] },
  { icon: '🍌', keywords: ['香蕉'] },
  { icon: '🍇', keywords: ['葡萄', '提子'] },
  { icon: '🍊', keywords: ['橙', '柑橘', '橘子', '桔子', '柚子'] },
  { icon: '🍓', keywords: ['草莓'] },
  { icon: '🫐', keywords: ['蓝莓'] },
  { icon: '🍒', keywords: ['樱桃', '车厘子'] },
  { icon: '🍉', keywords: ['西瓜'] },
  { icon: '🥭', keywords: ['芒果'] },
  { icon: '🍍', keywords: ['菠萝', '凤梨'] },
  { icon: '🍋', keywords: ['柠檬'] },
  { icon: '🍐', keywords: ['梨', '雪梨'] },
  { icon: '🍅', keywords: ['番茄', '西红柿'] },
  { icon: '🌶️', keywords: ['辣椒', '尖椒', '青椒', '红椒', '辣子'] },
  { icon: '🥒', keywords: ['黄瓜', '青瓜'] },
  { icon: '🍆', keywords: ['茄子'] },
  { icon: '🥕', keywords: ['胡萝卜', '红萝卜'] },
  { icon: '🥔', keywords: ['土豆', '马铃薯'] },
  { icon: '🍠', keywords: ['红薯', '地瓜', '紫薯', '番薯'] },
  { icon: '🌽', keywords: ['玉米'] },
  { icon: '🍄', keywords: ['蘑菇', '香菇', '金针菇', '木耳'] },
  { icon: '🥦', keywords: ['西兰花', '花菜', '菜花'] },
  { icon: '🥬', keywords: ['生菜', '菠菜', '青菜', '油菜', '白菜', '卷心菜'] },
  { icon: '🧅', keywords: ['洋葱'] },
  { icon: '🧄', keywords: ['蒜'] },
  { icon: '🥑', keywords: ['牛油果', '鳄梨'] },
  { icon: '🥜', keywords: ['花生', '坚果', '杏仁', '核桃', '腰果', '榛子'] },
  { icon: '🌰', keywords: ['栗子', '板栗'] },
  { icon: '🍞', keywords: ['面包', '吐司', '贝果', '欧包'] },
  { icon: '🥯', keywords: ['百吉饼'] },
  { icon: '🍚', keywords: ['米饭', '大米', '米粉', '白饭', '饭'] },
  { icon: '🍙', keywords: ['饭团'] },
  { icon: '🍛', keywords: ['咖喱'] },
  { icon: '🍜', keywords: ['面', '拉面', '意面', '乌冬', '荞麦面', '方便面'] },
  { icon: '🍝', keywords: ['意面', '意大利面'] },
  { icon: '🥟', keywords: ['饺子', '包子', '馒头', '馄饨', '小笼包', '生煎'] },
  { icon: '🍔', keywords: ['汉堡'] },
  { icon: '🍟', keywords: ['薯条', '薯片'] },
  { icon: '🍕', keywords: ['披萨', '比萨'] },
  { icon: '🌭', keywords: ['热狗'] },
  { icon: '🥪', keywords: ['三明治'] },
  { icon: '🌮', keywords: ['塔可', '卷饼'] },
  { icon: '🍗', keywords: ['鸡', '鸡腿', '鸡翅', '鸡胸', '炸鸡', '鸡肉'] },
  { icon: '🥩', keywords: ['牛', '牛排', '牛肉', '牛腩', '肥牛'] },
  { icon: '🥓', keywords: ['猪', '猪肉', '排骨', '里脊', '红烧肉', '腊肉', '火腿', '香肠'] },
  { icon: '🍖', keywords: ['肉', '烤肉', '羊排', '羊'] },
  { icon: '🥚', keywords: ['蛋', '鸡蛋', '茶叶蛋', '水煮蛋', '蛋挞'] },
  { icon: '🐟', keywords: ['鱼', '三文鱼', '鲈鱼', '鳕鱼', '金枪鱼', '带鱼'] },
  { icon: '🍤', keywords: ['虾', '虾仁', '龙虾', '海鲜', '蟹', '扇贝'] },
  { icon: '🦑', keywords: ['鱿鱼', '章鱼', '墨鱼'] },
  { icon: '🥛', keywords: ['奶', '牛奶', '酸奶', '奶酪', '芝士', '黄油', '奶油'] },
  { icon: '🥤', keywords: ['豆浆', '可乐', '汽水', '饮料', '苏打'] },
  { icon: '☕', keywords: ['咖啡'] },
  { icon: '🍵', keywords: ['茶', '绿茶', '红茶', '奶茶'] },
  { icon: '🧃', keywords: ['果汁'] },
  { icon: '🍺', keywords: ['啤酒'] },
  { icon: '🍷', keywords: ['葡萄酒', '红酒'] },
  { icon: '🍰', keywords: ['蛋糕', '甜点', '糕点'] },
  { icon: '🧁', keywords: ['纸杯蛋糕', '蛋糕'] },
  { icon: '🍦', keywords: ['冰淇淋', '雪糕', '冰棍'] },
  { icon: '🍫', keywords: ['巧克力'] },
  { icon: '🍬', keywords: ['糖', '糖果'] },
  { icon: '🍪', keywords: ['饼干', '曲奇'] },
  { icon: '🍯', keywords: ['蜂蜜'] },
  { icon: '🫒', keywords: ['橄榄油', '油'] },
  { icon: '🧂', keywords: ['盐', '糖', '酱', '调料', '酱油', '醋'] },
  { icon: '🍲', keywords: ['火锅', '汤', '煲汤', '麻辣烫'] },
  { icon: '🥗', keywords: ['沙拉', '色拉'] },
  { icon: '🥣', keywords: ['粥', '燕麦', '麦片', '米糊'] },
  { icon: '🧊', keywords: ['豆腐', '豆干', '豆皮', '腐竹'] },
  { icon: '🍶', keywords: ['酒', '白酒', '黄酒'] },
  { icon: '🥘', keywords: ['炖菜', '煲', '干锅'] },
  { icon: '🍳', keywords: ['煎蛋', '炒蛋', '蛋炒饭'] }
];

export function getFoodIcon(name) {
  const n = (name || '').toLowerCase();
  const flat = [];
  for (const item of ICON_MAP) {
    for (const kw of item.keywords) {
      flat.push({ icon: item.icon, keyword: kw.toLowerCase() });
    }
  }
  flat.sort((a, b) => b.keyword.length - a.keyword.length);
  for (const item of flat) {
    if (n.includes(item.keyword)) return item.icon;
  }
  return '🍽️';
}

export function getAllFoods() {
  const custom = getCustomFoods().map(f => ({ ...f, icon: getFoodIcon(f.name) }));
  return [...FOOD_DB, ...custom];
}
